service: recipes

provider:
  name: aws
  runtime: nodejs12.x
  cfnRole: arn:aws:iam::417867460222:role/serverlessRole
  stage: dev
  region: us-east-1

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get